# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Sample Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Add EC2 host key to known hosts
      run: |
          mkdir -p ~/.ssh
          echo "$EC2_INSTANCE_IP $(ssh-keyscan -t rsa $EC2_INSTANCE_IP 2>&1)" >> ~/.ssh/known_hosts
          
    - name: Deploy to EC2
      env:
          EC2_INSTANCE_IP: 54.235.7.161
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      run: |
          # Save the PEM key to a file
          echo "$EC2_SSH_PRIVATE_KEY" > key.pem
          chmod 400 key.pem

          # Add EC2 host key to known hosts
          ssh-keyscan -H $EC2_INSTANCE_IP >> ~/.ssh/known_hosts

          # Copy files and run commands on the remote EC2 instance
          scp -i key.pem app.py ubuntu@"$EC2_INSTANCE_IP":/home/ubuntu/
          ssh -i key.pem ubuntu@"$EC2_INSTANCE_IP" "python3 /home/ubuntu/app.py"

          # Clean up the PEM key file
          rm key.pem
          
      
